use super::*;

#[derive(Clone, Debug, PartialEq)]
pub struct VideoStyle {
    pub surface: WidgetSurfaceStyle,
    pub background: Value<Color>,
    pub border: Value<Color>,
    pub border_width: Dp,
    pub radius: Dp,
    pub padding: Insets,
    pub gap: Dp,
    pub controls_gap: Dp,
    pub overlay_background: Value<Color>,
    pub overlay_padding: Insets,
    pub overlay_gap: Dp,
    pub default_surface_width: Dp,
    pub default_surface_height: Dp,
    pub progress_height: Dp,
    pub progress_hit_height: Dp,
    pub progress_track_color: Value<Color>,
    pub progress_buffered_color: Value<Color>,
    pub progress_active_color: Value<Color>,
    pub progress_thumb_color: Value<Color>,
    pub volume_width: Dp,
    pub playback_rate_width: Dp,
    pub audio_track_width: Dp,
    pub subtitle_track_width: Dp,
    pub control_button_size: Dp,
    pub control_icon_size: Dp,
    pub control_icon_color: Value<Color>,
    pub control_icon_disabled_color: Value<Color>,
    pub control_disabled_opacity: f32,
    pub time_text_color: Value<Color>,
    pub status_text_color: Value<Color>,
    pub status_background: Value<Color>,
    pub status_padding: Insets,
    pub subtitle_text_color: Value<Color>,
    pub subtitle_background: Value<Color>,
    pub subtitle_padding: Insets,
    pub subtitle_bottom_offset: Dp,
    pub time_text_style: TextStyle,
    pub status_text_style: TextStyle,
    pub subtitle_text_style: TextStyle,
}

impl VideoStyle {
    pub fn default_for_theme(theme: &Theme) -> Self {
        Self {
            surface: WidgetSurfaceStyle::default(),
            background: Value::Static(Color::hexa(0x000000FF)),
            border: Value::Static(Color::TRANSPARENT),
            border_width: theme.border.none,
            radius: theme.radius.lg,
            padding: Insets::ZERO,
            gap: theme.spacing.sm,
            controls_gap: theme.spacing.xs,
            overlay_background: Value::Static(Color::hexa(0x000000B8)),
            overlay_padding: Insets::symmetric(theme.spacing.sm, theme.spacing.sm),
            overlay_gap: theme.spacing.xs,
            default_surface_width: dp(480.0),
            default_surface_height: dp(270.0),
            progress_height: dp(4.0),
            progress_hit_height: dp(18.0),
            progress_track_color: Value::Static(Color::hexa(0xFFFFFF38)),
            progress_buffered_color: Value::Static(Color::hexa(0xFFFFFF78)),
            progress_active_color: Value::Static(Color::hexa(0xFFFFFFFF)),
            progress_thumb_color: Value::Static(Color::hexa(0xFFFFFFFF)),
            volume_width: dp(92.0),
            playback_rate_width: dp(84.0),
            audio_track_width: dp(136.0),
            subtitle_track_width: dp(136.0),
            control_button_size: dp(32.0),
            control_icon_size: dp(20.0),
            control_icon_color: Value::Static(Color::hexa(0xFFFFFFFF)),
            control_icon_disabled_color: Value::Static(Color::hexa(0xFFFFFF9A)),
            control_disabled_opacity: 0.52,
            time_text_color: Value::Static(Color::hexa(0xFFFFFFFF)),
            status_text_color: Value::Static(Color::hexa(0xFFFFFFFF)),
            status_background: Value::Static(Color::hexa(0x0000008F)),
            status_padding: Insets::symmetric(theme.spacing.sm, theme.spacing.xs),
            subtitle_text_color: Value::Static(Color::hexa(0xFFFFFFFF)),
            subtitle_background: Value::Static(Color::hexa(0x000000B8)),
            subtitle_padding: Insets::symmetric(theme.spacing.sm, theme.spacing.xs),
            subtitle_bottom_offset: theme.spacing.md,
            time_text_style: theme.typography.label.clone(),
            status_text_style: theme.typography.label_small.clone(),
            subtitle_text_style: theme.typography.body_small.clone(),
        }
    }
}
